export const HANDLE_SELECT_QUIZ = 'HANDLE_SELECT_QUIZ';
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
export const HANDLE_SUBMIT_ANSWER = 'HANDLE_SUBMIT_ANSWER';
export const HANDLE_PREVIOUS_QUESTION = 'HANDLE_PREVIOUS_QUESTION';
export const HANDLE_NEXT_QUESTION = 'HANDLE_NEXT_QUESTION';
export const HANDLE_SUBMIT_ALL = 'HANDLE_SUBMIT_ALL';
