// QUIZ
export const HANDLE_SELECT_QUIZ = 'HANDLE_SELECT_QUIZ';
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
export const HANDLE_SUBMIT_ANSWER = 'HANDLE_SUBMIT_ANSWER';
export const HANDLE_PREVIOUS_QUESTION = 'HANDLE_PREVIOUS_QUESTION';
export const HANDLE_NEXT_QUESTION = 'HANDLE_NEXT_QUESTION';
export const HANDLE_SUBMIT_ALL = 'HANDLE_SUBMIT_ALL';

// FLASHCARD
export const HANDLE_SELECT_FLASHCARD_TOPIC = 'HANDLE_SELECT_FLASHCARD_TOPIC';
export const HANDLE_SHOW_BOX_CONTENT = 'HANDLE_SHOW_BOX_CONTENT';
export const HANDLE_PREVIOUS_FLASHCARD = 'HANDLE_PREVIOUS_FLASHCARD';
export const HANDLE_NEXT_FLASHCARD = 'HANDLE_NEXT_FLASHCARD';